##
# 安装基础软件
#
#
##
# @leif160519 @2020.08.29
# 默认配置用户为root，其他用户请跟参数-e username=ubuntu
####
---
- name: 系统设置
  hosts: all
  vars:
    username: root
  tags: config
  tasks:
    - name: 禁用swap分区(重启后生效) # {{{
      block:
        - replace:
            path: /etc/fstab
            regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
            replace: '# \1'
        - mount: # 仅对centos有效
            name: swap
            state: absent
            #shell: sed  -i '/swap/s/^/#/' /etc/fstab

        #- shell: swapoff -a #临时关闭

        #- name: 启用swap分区(重启后生效)
        #  replace:
        #    path: /etc/fstab
        #    regexp: '^# (.+?\sswap\s+sw\s+.*)$'
        #    replace: '\1'

        #- shell: swapon -a #临时启用
        # }}}

    - name: 配置SSH   # {{{
      block:
        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^#UseDNS'
            line: 'UseDNS no'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^#GSSAPIAuthentication'
            line: 'GSSAPIAuthentication no'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^#ClientAliveInterval'
            line: 'ClientAliveInterval 60'

        - lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^#ClientAliveCountMax'
            line: 'ClientAliveCountMax 60'

        - lineinfile:
            dest: /etc/ssh/ssh_config
            regexp: '^#   StrictHostKeyChecking'
            line: '    StrictHostKeyChecking no'

        - blockinfile:
            path: /etc/ssh/ssh_config
            block: |2
                  ServerAliveInterval 20
                  ServerAliveCountMax 999

        - service:
            name: sshd
            state: restarted
        # }}}

    - name: 修改Hostname # {{{
      block:
        - hostname:
            name: "{{ inventory_hostname }}"
      # }}}

    - name: 屏蔽系统错误报告 # {{{
      block:
        - file:
            path: /var/crash/
            state: absent
          when: ansible_distribution == "Ubuntu"

        - lineinfile:
            dest: /etc/default/apport
            regexp: '^enabled='
            line: 'enabled=0'
          when: ansible_distribution == "Ubuntu"
       # }}}

    - name: 设置当前用户执行sudo命令不需要密码 # {{{ 为何不直接修改sudoers文件:风险太大
      block:
        - lineinfile:
            dest: /etc/sudoers.d/{{ item }}
            create: yes
            line: '{{ item }} ALL=(ALL) NOPASSWD:ALL'
            mode: 0440
            owner: root
            group: root
          with_items:
            - "{{ username }}"
          when: not ( item is match "root" )
      # }}}

    - name: 禁用selinux(重启后生效) # {{{
      block:
        - lineinfile:
            dest: /etc/selinux/config
            regexp: '^SELINUX='
            line: 'SELINUX=disabled'
          when: ansible_os_family == "RedHat"
      # }}}

    - name : 禁用防火墙 #{{{
      block:
        - service:
            name: firewalld
            state: stopped
            enabled: no
          when: ansible_os_family == "RedHat"
      # }}}

    - name: 给pip换源 # {{{
      block:
        - file:
            path: ~{{ username }}/.pip
            state: directory
            owner: "{{ username }}"
            group: "{{ username }}"
            mode: 0755

        - file:
            path: ~{{ username }}/.pip/pip.conf
            state: touch
            owner: "{{ username }}"
            group: "{{ username }}"
            mode: 0755

        - blockinfile:
            path: ~{{ username }}/.pip/pip.conf
            owner: "{{ username }}"
            group: "{{ username }}"
            block: |
              [global]
              index-url = http://mirrors.aliyun.com/pypi/simple/
              [install]
              trusted-host=mirrors.aliyun.com
      # }}}

    - name: 配置关机等待时间 # {{{
      block:
        - lineinfile:
            dest: /etc/systemd/system.conf
            regexp: "^#DefaultTimeoutStartSec"
            line: "DefaultTimeoutStartSec=10s"

        - lineinfile:
            dest: /etc/systemd/system.conf
            regexp: "^#DefaultTimeoutStopSec"
            line: "DefaultTimeoutStopSec=10s"
      # }}}

    - name: 配置历史命令日期格式 # {{{
      lineinfile:
        path: ~{{ username }}/.bashrc
        line: 'export HISTTIMEFORMAT="%F %T "'
        owner: "{{ username }}"
        group: "{{ username }}"
      # }}}

    - name: 打开cron日志 # {{{
      block:
        - replace:
            path: /etc/rsyslog.d/50-default.conf
            regexp: "#cron"
            replace: "cron"
          when: ansible_distribution == "Ubuntu"

        - replace:
            path: /etc/rsyslog.conf
            regexp: "#cron"
            replace: "cron"
          when: (ansible_distribution == "Debian") or (ansible_os_family == "RedHat")

        - service:
            name: rsyslog
            state: restarted
            enabled: yes
      # }}}
